import { Inter } from 'next/font/google'
import './globals.css'
import ToasterProvider from '@/providers/ToasterProvider'
import { store } from '@/stores'
import { fetchUser } from '@/stores/user-store'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'YUNGA',
  description: 'Generated by me',
}

export default async function RootLayout({ children }) {
  await store.dispatch(fetchUser())
  console.log(store.getState().user)
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider/>
          {children}
      </body>
    </html>
  )
}
